### ISSUE TITLE
Wiki Images

### ISSUE THREAD

**Issue by Mrjimjr** [PurdueCAM2Project/Training#5]
Images can be uploaded here to be attached to wiki pages.

**Comment by Mrjimjr** [comment]
VM Wiki Images
VirtualBox Setup
![screen shot 2017-05-15 at 2 17 33 pm](https://cloud.githubusercontent.com/assets/9061978/26078657/34fd71ba-398e-11e7-9cca-419bd1d28ae2.png)
![screen shot 2017-05-15 at 2 15 45 pm](https://cloud.githubusercontent.com/assets/9061978/26078663/351693e8-398e-11e7-9467-737857762b6c.png)
![screen shot 2017-05-15 at 2 15 37 pm](https://cloud.githubusercontent.com/assets/9061978/26078660/351096aa-398e-11e7-8b7b-1404b7d37f7b.png)
![screen shot 2017-05-15 at 2 15 27 pm](https://cloud.githubusercontent.com/assets/9061978/26078659/350f1fc8-398e-11e7-80a7-8b50aa209a15.png)
![screen shot 2017-05-15 at 2 15 18 pm](https://cloud.githubusercontent.com/assets/9061978/26078658/350dde4c-398e-11e7-8fe3-9fba6d81cf27.png)
![screen shot 2017-05-15 at 2 15 09 pm](https://cloud.githubusercontent.com/assets/9061978/26078662/351636dc-398e-11e7-97af-1696ece27444.png)
![screen shot 2017-05-15 at 2 14 53 pm](https://cloud.githubusercontent.com/assets/9061978/26078661/35146ae6-398e-11e7-9160-f3c1476d36e3.png)
![screen shot 2017-05-15 at 2 14 26 pm](https://cloud.githubusercontent.com/assets/9061978/26078665/35220c14-398e-11e7-8deb-a7753c8e7361.png)
![screen shot 2017-05-15 at 2 14 09 pm](https://cloud.githubusercontent.com/assets/9061978/26078664/3520fe50-398e-11e7-9a98-f5406b17311d.png)


VMWare Setup
![1](https://cloud.githubusercontent.com/assets/9061978/26074477/f725b00e-397f-11e7-807f-b1afd8905758.JPG)
![2](https://cloud.githubusercontent.com/assets/9061978/26074473/f7238e78-397f-11e7-8daa-bb29277adb6b.JPG)
![3](https://cloud.githubusercontent.com/assets/9061978/26074474/f723ed8c-397f-11e7-80d7-90de1d2c8cfc.JPG)
![4](https://cloud.githubusercontent.com/assets/9061978/26074478/f725d7c8-397f-11e7-8241-0edcd40f14c4.JPG)
![5](https://cloud.githubusercontent.com/assets/9061978/26074475/f7244340-397f-11e7-8c99-32a2898142f6.JPG)
![6](https://cloud.githubusercontent.com/assets/9061978/26074476/f725b2c0-397f-11e7-82c0-bc9192c1efb5.JPG)
![7](https://cloud.githubusercontent.com/assets/9061978/26074479/f735aaae-397f-11e7-8ed7-729cfe77779a.JPG)
![8](https://cloud.githubusercontent.com/assets/9061978/26078322/1cd47184-398d-11e7-89df-c41d553b1cb4.JPG)

**Comment by ShengliSui** [comment]
![1-googlemapexample](https://cloud.githubusercontent.com/assets/9061978/26082670/1f4db92c-399f-11e7-8807-fd2bd0d2c2af.png)
![2-jsonexample](https://cloud.githubusercontent.com/assets/9061978/26082666/1f4c2c88-399f-11e7-9f89-c11b4a2ad432.png)
![3-cam745](https://cloud.githubusercontent.com/assets/9061978/26082671/1f4dc142-399f-11e7-95f4-207a09d98e66.png)
![4-cam745compaison](https://cloud.githubusercontent.com/assets/9061978/26082669/1f4d4ac8-399f-11e7-85b6-d801a5cf1bde.png)
![5-filloutheader](https://cloud.githubusercontent.com/assets/9061978/26082668/1f4d1e18-399f-11e7-9cb7-853c3d9fa961.png)
![6-importlib](https://cloud.githubusercontent.com/assets/9061978/26082667/1f4cbb58-399f-11e7-89a8-627b2a126ae0.png)
![7-setupoutputreaddata](https://cloud.githubusercontent.com/assets/9061978/26082672/1f559ae8-399f-11e7-97c0-fc851995b02e.png)
![8-loadjsonkeysintovar](https://cloud.githubusercontent.com/assets/9061978/26082675/1f5ab4b0-399f-11e7-997e-2a9aca5a6ae3.png)
![9-findingimagetag](https://cloud.githubusercontent.com/assets/9061978/26082674/1f5aa9d4-399f-11e7-8dbc-2b31dcc0ea45.png)
![10-readimgbs4](https://cloud.githubusercontent.com/assets/9061978/26082676/1f5bdc32-399f-11e7-983a-bf45cd890a6e.png)
![11-srccheck](https://cloud.githubusercontent.com/assets/9061978/26082673/1f58d0dc-399f-11e7-8c40-82dc14903ba4.png)
![12-headercorrections](https://cloud.githubusercontent.com/assets/9061978/26082677/1f5bdc6e-399f-11e7-936d-141fe82c6acc.png)
![13-platform](https://cloud.githubusercontent.com/assets/9061978/26082678/1f62402c-399f-11e7-96d7-9ecb1906c0db.png)
![14-pageloadcorrection](https://cloud.githubusercontent.com/assets/9061978/26082679/1f646ff0-399f-11e7-9530-bdfd36a324b0.png)
![15-correctoutput](https://cloud.githubusercontent.com/assets/9061978/26082681/1f65fa28-399f-11e7-8710-057e67e4ed8a.png)
![16-checkcameraactive](https://cloud.githubusercontent.com/assets/9061978/26082682/1f6a352a-399f-11e7-8e73-e3ca873c7d9e.png)
![17-finaloutput](https://cloud.githubusercontent.com/assets/9061978/26082680/1f65e6b4-399f-11e7-91fd-610a17ab6d23.png)

**Comment by Mrjimjr** [comment]
Selenium Assignment
![4-camerainspect](https://cloud.githubusercontent.com/assets/9061978/26108719/5847c41c-3a1b-11e7-8bd6-46be52801b86.jpg)
![3-mapinspect](https://cloud.githubusercontent.com/assets/9061978/26108724/594fb0c2-3a1b-11e7-8865-22aebcb8aa91.jpg)
![2-map](https://cloud.githubusercontent.com/assets/9061978/26108720/585932f6-3a1b-11e7-8317-d88f3cfa3b96.jpg)
![1-timessquare](https://cloud.githubusercontent.com/assets/9061978/26108721/5864bc70-3a1b-11e7-81e3-0133afc90128.jpg)
